### ISSUE TITLE
austin-tui raises exception: _curses.error: init_pair() returned ERR

### ISSUE THREAD

**Issue by westhomas** [P403n1x87/austin#49]
### Description

Trying to run austin against existing python3 process running in a docker container raises an exception with curses initialization. 

### Steps to Reproduce

1. Run target app in docker container

2. Run austin-tui and pass PID

````
$ docker-compose exec app bash -c "austin-tui -p 1"
````

3. See exception

**Expected behavior:** 
Seeing TUI screen

**Actual behavior:**

```
Traceback (most recent call last):
  File "/usr/local/bin/austin-tui", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/austin/main.py", line 23, in main
    curses.wrapper(lambda scr: curses_app(scr, parsed_args))
  File "/usr/local/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/austin/main.py", line 23, in <lambda>
    curses.wrapper(lambda scr: curses_app(scr, parsed_args))
  File "/usr/local/lib/python3.6/site-packages/austin/main.py", line 9, in curses_app
    with AustinTUI(scr) as austin_tui:
  File "/usr/local/lib/python3.6/site-packages/austin/tui.py", line 333, in __enter__
    curses.init_pair(color, *values)
_curses.error: init_pair() returned ERR
```

**Reproduces how often:**

100%

### Versions

```
$ dc exec app bash -c "austin --version"
austin 1.0.1
$ dc exec app bash -c "lsb_release -a"
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

**Comment by P403n1x87** [comment]
Hi and thanks for reporting this issue. Would the suggestion posted in [this bug](https://github.com/xoreaxeaxeax/sandsifter/issues/14) help in this case, that is, `export TERM='xterm-256color'` before starting the TUI?

**Comment by Hierosme** [comment]
Hello,

That clearly because the virtual terminal not support color, in that case you should use ``curses.use_default_colors()`` where in that case all color pair will be translate to **BLACK** and **WHITE** color pair **ZERO**

The workarround about export TERM="xterm-256color" work but that not fixe the trouble considering the code it init color pair.

Here how i do:

``` python
        try:
            if curses.has_colors():
                curses.start_color()

                curses.init_pair(0, curses.COLOR_WHITE, curses.COLOR_BLACK)
                for bg in [0, 1, 2, 3, 4, 5, 6, 7]:
                    for fg in [0, 1, 2, 3, 4, 5, 6, 7]:
                        curses.init_pair(self.curses_color_pair_number(fg, bg),
                                         self.curses_color(fg),
                                         self.curses_color(bg)
                                         )
            else:
                curses.init_pair(0, curses.COLOR_WHITE, curses.COLOR_BLACK)
        except curses.error:
            curses.use_default_colors()
```

in summary:

```
try:
    #INIT COLOR HERE
except curses.error:
    curses.use_default_colors()
```
about the TERM  here how i do:

```
    @staticmethod
    def check_terminal(force_xterm=False):
        termvalue = os.environ.get("TERM")

        if not termvalue:
            raise EnvironmentError("'TERM' variable is not set")
        if termvalue == 'xterm':
            # activate 256 colors
            termvalue += '-256color'
            os.environ["TERM"] = termvalue
        # xdisplay = os.environ.get('DISPLAY')

        return (
            force_xterm
            or "xterm" in termvalue
            or "xterm-256color" in termvalue
            or "konsole" in termvalue
            or "rxvt" in termvalue
            or "Eterm" in termvalue
            or "dtterm" in termvalue
            or "screen" in termvalue
            and os.environ.get("DISPLAY")
        )
```

I hope it help, take a look on Galaxie-Curses project: https://gitlab.com/Tuuux/galaxie-curses

Regards

**Comment by Hierosme** [comment]
The trouble is on the __enter__ function

``` python
    def __enter__(self):
        super().__enter__()

        for color, values in PALETTE.items():
            curses.init_pair(color, *values)

        j = Color.HEAT_ACTIVE
        for i in [-1, 226, 208, 202, 196]:
            curses.init_pair(j, i, -1)
            j += 1
        j = Color.HEAT_INACTIVE
        for i in [246, 100, 130, 94, 88]:
            curses.init_pair(j, i, -1)
            j += 1

        return self
```

should be something like

```
    def __enter__(self):
        super().__enter__()
        try:
            for color, values in PALETTE.items():
                curses.init_pair(color, *values)

            j = Color.HEAT_ACTIVE
            for i in [-1, 226, 208, 202, 196]:
                curses.init_pair(j, i, -1)
                j += 1
            j = Color.HEAT_INACTIVE
            for i in [246, 100, 130, 94, 88]:
                curses.init_pair(j, i, -1)
                j += 1
    except curses.error:
        curses.use_default_colors()
    return self
```
